# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ocean's Heart
email: max.mraz.11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ocean's Heart in an Action RPG about exploring a sprawling, quirky archipelago
  full of pirates, magic, and sidequests to find your dad. You'll find many new
  weapons, powers, conspiracies, and charm and you piece together your dad's trail.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maxmraz.github.io/oceansheart" # the base hostname & protocol for your site
twitter_username: 11mraz
github_username:  MaxMraz

# Build settings
markdown: kramdown
